### ISSUE TITLE
Django 3.0+ Uses deprecated postgresql_psycopg2 package

### ISSUE THREAD

**Issue by jkleve** [jazzband/dj-database-url#131]
I'm getting this error 

```
Traceback (most recent call last):
  File "/Users/jesse.kleve/src/playgrounds/django/dori/api/venv/lib/python3.7/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
    self.connect()
  File "/Users/jesse.kleve/src/playgrounds/django/dori/api/venv/lib/python3.7/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/Users/jesse.kleve/src/playgrounds/django/dori/api/venv/lib/python3.7/site-packages/django/db/backends/base/base.py", line 197, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/Users/jesse.kleve/src/playgrounds/django/dori/api/venv/lib/python3.7/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/Users/jesse.kleve/src/playgrounds/django/dori/api/venv/lib/python3.7/site-packages/django/db/backends/postgresql/base.py", line 185, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/Users/jesse.kleve/src/playgrounds/django/dori/api/venv/lib/python3.7/site-packages/psycopg2/__init__.py", line 125, in connect
    dsn = _ext.make_dsn(dsn, **kwargs)
  File "/Users/jesse.kleve/src/playgrounds/django/dori/api/venv/lib/python3.7/site-packages/psycopg2/extensions.py", line 174, in make_dsn
    parse_dsn(dsn)
psycopg2.ProgrammingError: invalid dsn: invalid connection option "init_command"
```

It seems to be using the wrong backend. It's using `'django.db.backends.postgresql_psycopg2'` with `DATABASE_URL='postgres://root:toor@127.0.0.1:5432/django'`.

This is with Django version 3.0

**Comment by jkleve** [comment]
It appears this is fixed in master?

Any plan for the next release?

**Comment by ovnicraft** [comment]
@jkleve do you know  where is the fix in master ? to check if it possible a backport

**Comment by wsvincent** [comment]
Hi y'all,

This issue should be closed. This package is handling it correctly. Since Django 1.9, the alias `django.db.backends.postgresql` has been used instead of `django.db.backends.postgresql_psycogp2`. You can see that in the `dj_database_url.py` file and read more in the [Django 3.0 release notes](https://docs.djangoproject.com/en/3.0/releases/2.0/#id1).

-WIll

**Comment by jkleve** [comment]
@wsvincent I see the fix on master but the latest release (0.5.0) does not include the fix. 

Right? Or am I missing something?
[0.5.0](https://github.com/jacobian/dj-database-url/blob/de91c7de55a416fff305a4cb8abf8e8f67f452e8/dj_database_url.py#L30)
[master](https://github.com/jacobian/dj-database-url/blob/1937ed9e61d273163353c8546825dd529ce8546c/dj_database_url.py#L54)

**Comment by jkleve** [comment]
@ovnicraft Sorry missed your comment. See "master" link above.

**Comment by amrishparmar** [comment]
I'm running into the same issue at the moment. Any chance of a new release? As already mentioned, the current PyPI version (0.5.0) is still using the old behaviour even though this is fixed on `master`.

**Comment by Moulde** [comment]
You can optionally install the package directly from git like so
`git+https://github.com/jacobian/dj-database-url.git#egg=dj_database_url`

**Comment by alexanderGerbik** [comment]
The new version https://pypi.org/project/dj-database-url/1.0.0/ is out on pypi, which includes the fix, so the issue can be closed.
